name: Release
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Level of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - test

jobs:
  version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.versioning.outputs.NEW_VER }}

    steps:
      - name: Generate Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: temurin
          server-id: 'github'

      - name: Calculate & Set New Version
        id: versioning
        shell: bash
        run: |
          CURRENT_VER=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          IFS='.' read -ra ADDR <<< "$CURRENT_VER"
          MAJOR=${ADDR[0]}
          MINOR=${ADDR[1]}
          PATCH=${ADDR[2]}
          
          if [[ "${{ github.event.inputs.bump_type }}" == "major" ]]; then
            NEW_VER="$((MAJOR + 1)).0.0"
          elif [[ "${{ github.event.inputs.bump_type }}" == "minor" ]]; then
            NEW_VER="$MAJOR.$((MINOR + 1)).0"
          elif [[ "${{ github.event.inputs.bump_type }}" == "patch" ]]; then
            NEW_VER="$MAJOR.$MINOR.$((PATCH + 1))"
          else
            NEW_VER="$MAJOR.$MINOR.$PATCH.test"
          fi
          
          echo "NEW_VER=$NEW_VER" >> $GITHUB_OUTPUT
          mvn versions:set -DnewVersion=$NEW_VER -DgenerateBackupPoms=false

      - name: Commit & Push to Development
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git commit -am "[ACTION] bump version to ${{ steps.versioning.outputs.NEW_VER }}"
          git push origin main
          
          git tag pom-v${{ steps.versioning.outputs.NEW_VER }}
          git push origin pom-v${{ steps.versioning.outputs.NEW_VER }}

      - name: Squash Merge Into Releases
        shell: bash
        run: |
          git fetch origin releases
          git checkout releases
          
          git merge --squash main
          
          git commit -m "Release v${{ steps.versioning.outputs.NEW_VER }}"
          git push origin releases

      - name: Tag it
        shell: bash
        run: |
          git tag release-v${{ steps.versioning.outputs.NEW_VER }}
          git push origin release-v${{ steps.versioning.outputs.NEW_VER }}
          

  build:
    needs: version-bump
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: release-v${{ needs.version-bump.outputs.new_version }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Build JAR
        run: mvn -B clean package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: target/*.jar

  package-and-release:
    needs: [version-bump, build]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    permissions:
      contents: write

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: jar
          path: .

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Package
        shell: bash
        run: |
          rm -rf dist bundle runtime app.jar
          mkdir -p dist
          
          VER=${{ needs.version-bump.outputs.new_version }}
          
          JAR=$(find . -name "*.jar" | head -n 1}
          cp "$JAR" app.jar
          
          jlink \
            --add-modules java.base,java.desktop,java.logging,java.net.http,jdk.unsupported,jdk.crypto.ec,jdk.charsets,java.management,java.scripting,jdk.jsobject \
            --output runtime \
            --strip-debug \
            --no-header-files \
            --no-man-pages
          
          mkdir -p bundle
          mv runtime bundle/jre
          mv app.jar bundle/
          
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "@echo off" > bundle/start.bat
            echo "jre\\bin\\java -jar app.jar" >> bundle/start.bat
            7z a "dist/ui-${VER}-windows.zip" ./bundle/*
          else
            echo "#!/bin/sh" > bundle/start.sh
            echo "./jre/bin/java -jar app.jar" >> bundle/start.sh
            chmod +x bundle/start.sh
          
            OS_NAME="linux"
            [[ "${{ matrix.os }}" == "macos-latest" ]] && OS_NAME="macos"
          
            cd bundle && zip -r "../dist/ui-${VER}-${OS_NAME}.zip" . && cd ..
          fi

      - name: Upload to Single Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-v${{ needs.version-bump.outputs.new_version }}
          files: dist/*
          append_body: true
          make_latest: true
          name: ${{ steps.tags.outputs.name }}
          generate_release_notes: ${{ matrix.os == 'ubuntu-latest' }}
          draft: ${{ github.event.inputs.bump_type  == 'test' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

